services:
  mysql:
    image: mysql:8
    ports:
      - 8083:3306
    volumes:
      - mysql-data:/var/lib/librarydb
      - ./hw17/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarydb

volumes:
  mysql-data:
